export {default as Meta} from './Global/Meta';
export {default as Header} from './Global/Header';
export {default as Hero} from './Hero';
export {default as Profile} from './Profile';
export {default as Galery} from './Galery';
export {default as Review} from './Review';
export {default as Courses} from './Courses';
export {default as Footer} from './Footer';
export {default as Banner} from './Banner';